### ISSUE TITLE
".local" domain should not be used

### ISSUE THREAD

**Issue by torounit** [littlebirdjp/vccw-env-for-theme-build#1]
Should use other domain like ".dev", ".test", ".localhost".

see [Mac が参加するADのドメイン名で .local を使わないでください。](https://www.picturecode.co.jp/faq/dot-local-domain/)

[Change TLD for test sites · Issue #583 · Varying-Vagrant-Vagrants/VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/583)

**Comment by youthkee** [comment]
Thank you for your information!
I'll rebuild the environment later.

**Comment by Sacro** [comment]
Should **not** use .dev

https://chromium-review.googlesource.com/c/chromium/src/+/669923
